// Auto-generated by PROMPT 64 at 2025-08-12T08:08:37.716Z
// Vybrané lazy moduly na idle preload (max 5). Úpravy sú bezpečné – systém je opt-in (VITE_PRELOAD=1).
export const preloaders = [
  () => import('../components/analytics/AnalyticsDashboard'),
  () => import('../components/dashboard/Dashboard'),
  () => import('./features/dashboard/components/Dashboard'),
  () => import('./features/subscriptions/components/SubscriptionDashboard'),
  () => import('./features/assets-vault/components/VaultDashboard')
];
export default preloaders;
